
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/usb_c/inc

obj-$(CONFIG_USB_C_SWITCH_FUSB302) += fusb302/
obj-$(CONFIG_USB_C_SWITCH_SII70XX) += sii7033/
obj-$(CONFIG_USB_C_SWITCH_ANX7418) += anx7418/
obj-$(CONFIG_USB_C_SWITCH_MT6353)  += mt6353/
# [Arima_8103][bozhi_lin] TUSB320 TypeC driver porting 20170510 begin
obj-$(CONFIG_USB_C_SWITCH_TUSB320) += tusb320/
# [Arima_8103][bozhi_lin] 20170510 end
